version: '3.8'

services:
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sql
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: sql
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  frontend:
          build:
            context: C:\Users\MCARDAUC\Desktop\front-app
            dockerfile: Dockerfile
          container_name: react-frontend
          ports:
          - "3000:80"
          networks:
            - app-network
          depends_on:
            - app

networks:
  app-network:

volumes:
  db_data:
