version: '3.8'

services:
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sql
    depends_on:
      - mysql
    volumes:
      - logs_data:/app
      - ./public/userProfileImages:/app/public/userProfileImages
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: sql
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    networks:
      - app-network

  frontend:
          build:
            context: C:\Users\MCARDAUC\Desktop\front-app
            dockerfile: Dockerfile
          container_name: react-frontend
          ports:
          - "3000:80"
          networks:
            - app-network
          depends_on:
            - app


  fluentd:
    image: fluent/fluentd:v1.14-1
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - logs_data:/app/logs:ro
      - D:/fluentd/fluentd.conf:/fluentd/etc/fluent.conf

networks:
  app-network:

volumes:
  logs_data:
