# Use the official Fluentd base image
FROM fluent/fluentd:v1.14-1

# Switch to root for privileged operations
USER root

# Install necessary dependencies and Fluentd plugins with SSL verification disabled
RUN apk update \
    && apk add --no-cache \
       ca-certificates \
       ruby ruby-irb ruby-etc ruby-webrick \
       tini \
    && apk add --no-cache --virtual .build-deps \
       build-base linux-headers ruby-dev gnupg \
    && echo 'gem: --no-document' >> /etc/gemrc \
    && gem install oj -v 3.16.1 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install json -v 2.6.3 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install rexml -v 3.2.6 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install async -v 1.31.0 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install traces -v 0.11.1 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install async-http -v 0.50.0 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install uri -v 0.12.2 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install fluentd -v 1.16.3 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install bigdecimal -v 1.4.4 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install prometheus-client -v 4.2.2 --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install fluent-plugin-grafana-loki --no-document --source http://rubygems.org -- --no-check-certificate \
    && gem install fluent-plugin-prometheus --no-document --source http://rubygems.org -- --no-check-certificate \
    && fluent-gem list | grep fluent-plugin-prometheus \
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

# Set up Fluentd directories and permissions
RUN adduser -S -G fluent fluent || true \
   && mkdir -p /fluentd/log /fluentd/etc /fluentd/plugins \
   && chown -R fluent /fluentd && chgrp -R fluent /fluentd

# Copy Fluentd configuration and set permissions
COPY fluentd.conf /fluentd/etc/fluent.conf
RUN chown fluent:fluent /fluentd/etc/fluent.conf

# Expose ports for Fluentd (metrics on 24231)
EXPOSE 24231 5140

# Switch back to the non-root user for running the container
USER fluent

# Set environment variables
ENV FLUENTD_CONF="fluent.conf"
ENV LD_PRELOAD=""

# Run Fluentd
CMD ["fluentd", "-c", "/fluentd/etc/fluent.conf"]
