global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus' 
    static_configs:
    - targets: ['host.docker.internal:8080']

  - job_name: 'fluentd'
    static_configs:
      - targets: ['fluentd:24231']